language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t itilya/fib-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true itilya/fib-test npm test

after_success:
  - docker build -t itilya/fibonachi-app ./client
  - docker build -t itilya/fibonachi-nginx ./nginx
  - docker build -t itilya/fibonachi-server ./server
  - docker build -t itilya/fibonachi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # TAke images and push them to docker hub
  - docker push itilya/fibonachi-app ./client
  - docker push itilya/fibonachi-nginx ./nginx
  - docker push itilya/fibonachi-server ./server
  - docker push itilya/fibonachi-worker ./worker


