language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t itilya/fib-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true itilya/fib-test npm test

after_success:
  - docker build -t itilya/fibonachi-app ./client
  - docker build -t itilya/fibonachi-nginx ./nginx
  - docker build -t itilya/fibonachi-server ./server
  - docker build -t itilya/fibonachi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # TAke images and push them to docker hub
  - docker push itilya/fibonachi-app
  - docker push itilya/fibonachi-nginx
  - docker push itilya/fibonachi-server
  - docker push itilya/fibonachi-worker

  deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-196174624845'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY


